TEXTOS = {
    "Español": {
        "menu_dash": "📊 Dashboard 360",
        "titulo_dash": "Visión Global del Negocio",
        "subtitulo_dash": "Métricas clave en tiempo real",
        "menu_ia": "🧠 Análisis Inteligente",
        "menu_proyectos": "🚧 Proyectos (Obras)",
        "menu_inventario": "📦 Inventario",
        "menu_rrhh": "👥 Gestión Personal",
        "menu_subir": "📤 Subir Gasto",
        "menu_horas": "⏱️ Fichar Horas",
        "menu_presu": "📝 Presupuestos",
        "menu_flota": "🚛 Flota",
        "menu_herra": "🛠️ Utilidades",

        "lbl_quien_sube": "¿Quién sube el ticket?",
        "lbl_proyecto": "🏗️ Proyecto / Obra",
        "lbl_pais": "País del Gasto",
        "lbl_categoria": "Categoría",
        "lbl_subir_box": "Sube la foto del ticket o factura",
        "lbl_vista_previa": "Vista previa del documento",
        "btn_procesar_ia": "⚡ Procesar con IA",
        "err_falta_nombre": "⚠️ Por favor, indica el nombre del empleado.",
        "msg_analizando": "🤖 Analizando documento con Azure Intelligence...",
        "msg_exito": "✅ ¡Guardado correctamente!",

        "horas_titulo": "⏱️ Parte de Horas",
        "lbl_empleado": "Empleado",
        "lbl_fecha_horas": "Fecha",
        "lbl_horas_trab": "Horas Trabajadas",
        "lbl_desc_tarea": "Descripción de la Tarea",
        "ph_desc_tarea": "Ej: Pintar fachada, Viaje, Compras...",
        "btn_guardar_horas": "💾 Guardar Parte de Horas",

        "tool_titulo_precios": "⛽ Precios Combustible",
        "tool_titulo_roi": "🧮 Calculadora Viajes",
        "btn_gasolineras": "Ver precios Gasolina (Europa)",
        "btn_cargadores": "Mapa Cargadores Eléctricos",
        "header_accesos": "Accesos Profesionales",
        "lbl_consumo": "Consumo (L/100km)",
        "lbl_precio_gas": "Precio Gasolina/Diesel",
        "lbl_precio_hora": "Coste Hora Empleado",
        "lbl_km_extra": "Km Extra (Ida/Vuelta)",
        "lbl_desc_prod": "Descuento en Producto",
        "lbl_min_extra": "Minutos Extra (Conducir)",
        "res_coste_viaje": "Coste Real del Viaje",
        "res_si_compensa": "✅ SÍ compensa viajar. Ahorras:",
        "res_no_compensa": "❌ NO compensa. Pierdes:"
    },

    "Deutsch": {
        "menu_dash": "📊 Dashboard 360",
        "titulo_dash": "Geschäftsüberblick",
        "subtitulo_dash": "Wichtige Kennzahlen in Echtzeit",
        "menu_ia": "🧠 Intelligente Analyse",
        "menu_proyectos": "🚧 Projekte (Baustellen)",
        "menu_inventario": "📦 Inventar",
        "menu_rrhh": "👥 Personalverwaltung",
        "menu_subir": "📤 Ausgabe hochladen",
        "menu_horas": "⏱️ Stunden erfassen",
        "menu_presu": "📝 Angebote",
        "menu_flota": "🚛 Fuhrpark",
        "menu_herra": "🛠️ Werkzeuge",

        "lbl_quien_sube": "Wer lädt hoch?",
        "lbl_proyecto": "🏗️ Projekt / Baustelle",
        "lbl_pais": "Land der Ausgabe",
        "lbl_categoria": "Kategorie",
        "lbl_subir_box": "Foto des Belegs hochladen",
        "lbl_vista_previa": "Vorschau",
        "btn_procesar_ia": "⚡ Mit KI verarbeiten",
        "err_falta_nombre": "⚠️ Bitte geben Sie den Namen des Mitarbeiters an.",
        "msg_analizando": "🤖 Analysiere Dokument mit Azure...",
        "msg_exito": "✅ Erfolgreich gespeichert!",

        "horas_titulo": "⏱️ Arbeitszeit erfassen",
        "lbl_empleado": "Mitarbeiter",
        "lbl_fecha_horas": "Datum",
        "lbl_horas_trab": "Arbeitsstunden",
        "lbl_desc_tarea": "Beschreibung der Tätigkeit",
        "ph_desc_tarea": "Z.B. Fassade streichen, Reise...",
        "btn_guardar_horas": "💾 Stunden speichern",

        "tool_titulo_precios": "⛽ Kraftstoffpreise",
        "tool_titulo_roi": "🧮 Reisekostenrechner",
        "btn_gasolineras": "Benzinpreise (Europa)",
        "btn_cargadores": "Ladestationen Karte",
        "header_accesos": "Profi-Zugänge",
        "lbl_consumo": "Verbrauch (L/100km)",
        "lbl_precio_gas": "Benzinpreis",
        "lbl_precio_hora": "Stundensatz",
        "lbl_km_extra": "Zusätzliche Km",
        "lbl_desc_prod": "Produkt Rabatt",
        "lbl_min_extra": "Zusätzliche Minuten",
        "res_coste_viaje": "Reisekosten",
        "res_si_compensa": "✅ Lohnt sich. Ersparnis:",
        "res_no_compensa": "❌ Lohnt sich NICHT. Verlust:"
    },

    "Galego": {
        "menu_dash": "📊 Panel 360",
        "titulo_dash": "Visión Global do Negocio",
        "subtitulo_dash": "Métricas clave en tempo real",
        "menu_ia": "🧠 Análise Intelixente",
        "menu_proyectos": "🚧 Proxectos (Obras)",
        "menu_inventario": "📦 Inventario",
        "menu_rrhh": "👥 Xestión Persoal",
        "menu_subir": "📤 Subir Gasto",
        "menu_horas": "⏱️ Fichar Horas",
        "menu_presu": "📝 Orzamentos",
        "menu_flota": "🚛 Frota",
        "menu_herra": "🛠️ Utilidades",

        "lbl_quien_sube": "Quen sube o ticket?",
        "lbl_proyecto": "🏗️ Proxecto / Obra",
        "lbl_pais": "País do Gasto",
        "lbl_categoria": "Categoría",
        "lbl_subir_box": "Sube a foto do ticket ou factura",
        "lbl_vista_previa": "Vista previa do documento",
        "btn_procesar_ia": "⚡ Procesar con IA",
        "err_falta_nombre": "⚠️ Por favor, indica o nome do empregado.",
        "msg_analizando": "🤖 Analizando documento con Azure Intelligence...",
        "msg_exito": "✅ Gardado correctamente!",

        "horas_titulo": "⏱️ Parte de Horas",
        "lbl_empleado": "Empregado",
        "lbl_fecha_horas": "Data",
        "lbl_horas_trab": "Horas Traballadas",
        "lbl_desc_tarea": "Descrición da Tarefa",
        "ph_desc_tarea": "Ex: Pintar fachada, Viaxe, Compras...",
        "btn_guardar_horas": "💾 Gardar Parte de Horas",

        "tool_titulo_precios": "⛽ Prezos Combustible",
        "tool_titulo_roi": "🧮 Calculadora Viaxes",
        "btn_gasolineras": "Ver prezos Gasolina (Europa)",
        "btn_cargadores": "Mapa Cargadores Eléctricos",
        "header_accesos": "Accesos Profesionais",
        "lbl_consumo": "Consumo (L/100km)",
        "lbl_precio_gas": "Prezo Gasolina/Diesel",
        "lbl_precio_hora": "Custo Hora Empregado",
        "lbl_km_extra": "Km Extra (Ida/Volta)",
        "lbl_desc_prod": "Desconto en Produto",
        "lbl_min_extra": "Minutos Extra (Conducir)",
        "res_coste_viaje": "Custo Real da Viaxe",
        "res_si_compensa": "✅ SI compensa viaxar. Aforras:",
        "res_no_compensa": "❌ NON compensa. Perdes:"
    },

    "English": {
        "menu_dash": "📊 Dashboard 360",
        "titulo_dash": "Business Overview",
        "subtitulo_dash": "Key metrics in real-time",
        "menu_ia": "🧠 Smart Analysis",
        "menu_proyectos": "🚧 Projects (Sites)",
        "menu_inventario": "📦 Inventory",
        "menu_rrhh": "👥 HR Management",
        "menu_subir": "📤 Upload Expense",
        "menu_horas": "⏱️ Log Hours",
        "menu_presu": "📝 Quotes / Estimates",
        "menu_flota": "🚛 Fleet",
        "menu_herra": "🛠️ Tools",

        "lbl_quien_sube": "Who is uploading?",
        "lbl_proyecto": "🏗️ Project / Site",
        "lbl_pais": "Expense Country",
        "lbl_categoria": "Category",
        "lbl_subir_box": "Upload receipt or invoice photo",
        "lbl_vista_previa": "Document Preview",
        "btn_procesar_ia": "⚡ Process with AI",
        "err_falta_nombre": "⚠️ Please indicate employee name.",
        "msg_analizando": "🤖 Analyzing document with Azure Intelligence...",
        "msg_exito": "✅ Saved successfully!",

        "horas_titulo": "⏱️ Timesheet",
        "lbl_empleado": "Employee",
        "lbl_fecha_horas": "Date",
        "lbl_horas_trab": "Hours Worked",
        "lbl_desc_tarea": "Task Description",
        "ph_desc_tarea": "Ex: Painting facade, Travel, Supplies...",
        "btn_guardar_horas": "💾 Save Timesheet",

        "tool_titulo_precios": "⛽ Fuel Prices",
        "tool_titulo_roi": "🧮 Travel Calculator",
        "btn_gasolineras": "Check Gas Prices (Europe)",
        "btn_cargadores": "EV Chargers Map",
        "header_accesos": "Pro Access",
        "lbl_consumo": "Consumption (L/100km)",
        "lbl_precio_gas": "Fuel Price",
        "lbl_precio_hora": "Hourly Labor Cost",
        "lbl_km_extra": "Extra Km (Round trip)",
        "lbl_desc_prod": "Product Discount",
        "lbl_min_extra": "Extra Minutes (Driving)",
        "res_coste_viaje": "Real Trip Cost",
        "res_si_compensa": "✅ YES, worth it. You save:",
        "res_no_compensa": "❌ NOT worth it. You lose:"
    }
}