[pytest]
pythonpath = .
testpaths = tests
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
filterwarnings =
    ignore::DeprecationWarning:passlib.utils.*
    ignore::DeprecationWarning:storage3.types
    ignore::DeprecationWarning:jose.jwt
