[pytest]
pythonpath = .
testpaths = tests
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
filterwarnings =
    ignore::DeprecationWarning:storage3.types
    ignore::DeprecationWarning:jose.jwt
    ignore:'cgi' is deprecated and slated for removal in Python 3.13:DeprecationWarning:zeep.utils
