BEGIN;

ALTER TABLE public.flota
  ADD COLUMN IF NOT EXISTS engine_class varchar(32) NOT NULL DEFAULT 'EURO_VI',
  ADD COLUMN IF NOT EXISTS fuel_type varchar(32) NOT NULL DEFAULT 'DIESEL';

ALTER TABLE public.portes
  ADD COLUMN IF NOT EXISTS km_vacio numeric(12,3) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS subcontratado boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS public.webhook_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider varchar(64) NOT NULL,
  event_type varchar(128) NOT NULL,
  payload jsonb NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'pending',
  error_log text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_webhook_events_status_created_at
  ON public.webhook_events (status, created_at);

CREATE INDEX IF NOT EXISTS idx_webhook_events_provider_event_type
  ON public.webhook_events (provider, event_type);

COMMIT;
