BEGIN;

CREATE TABLE IF NOT EXISTS public.finance_kpi_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id uuid NOT NULL,
  period_month text NOT NULL CHECK (period_month ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  ingresos_operacion numeric(18,2) NOT NULL DEFAULT 0,
  gastos_operacion numeric(18,2) NOT NULL DEFAULT 0,
  ebitda numeric(18,2) NOT NULL DEFAULT 0,
  last_recalculated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ux_finance_kpi_snapshots_empresa_period UNIQUE (empresa_id, period_month)
);

CREATE INDEX IF NOT EXISTS idx_finance_kpi_snapshots_empresa_month
  ON public.finance_kpi_snapshots (empresa_id, period_month);

CREATE OR REPLACE FUNCTION public.round_half_even(p_value numeric, p_scale int DEFAULT 2)
RETURNS numeric
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  v_factor numeric;
  v_shifted numeric;
  v_abs numeric;
  v_floor numeric;
  v_frac numeric;
  v_rounded numeric;
  v_sign numeric;
BEGIN
  IF p_value IS NULL THEN
    RETURN NULL;
  END IF;
  IF p_scale < 0 THEN
    RAISE EXCEPTION 'p_scale must be >= 0';
  END IF;

  v_factor := power(10::numeric, p_scale);
  v_shifted := p_value * v_factor;
  v_sign := CASE WHEN v_shifted < 0 THEN -1 ELSE 1 END;
  v_abs := abs(v_shifted);
  v_floor := trunc(v_abs);
  v_frac := v_abs - v_floor;

  IF v_frac > 0.5 THEN
    v_rounded := v_floor + 1;
  ELSIF v_frac < 0.5 THEN
    v_rounded := v_floor;
  ELSE
    IF mod(v_floor::numeric, 2) = 0 THEN
      v_rounded := v_floor;
    ELSE
      v_rounded := v_floor + 1;
    END IF;
  END IF;

  RETURN (v_rounded * v_sign) / v_factor;
END;
$$;

CREATE OR REPLACE FUNCTION public._upsert_monthly_kpis(
  p_empresa_id uuid,
  p_period_month text
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_ingresos numeric(18,2);
  v_gastos numeric(18,2);
  v_ebitda numeric(18,2);
BEGIN
  IF p_empresa_id IS NULL OR p_period_month IS NULL OR p_period_month !~ '^\d{4}-(0[1-9]|1[0-2])$' THEN
    RETURN;
  END IF;

  SELECT
    COALESCE(sum(
      public.round_half_even(
        CASE
          WHEN f.base_imponible IS NOT NULL THEN f.base_imponible
          ELSE GREATEST(COALESCE(f.total_factura, 0) - COALESCE(f.cuota_iva, 0), 0)
        END,
        2
      )
    ), 0)::numeric(18,2)
  INTO v_ingresos
  FROM public.facturas f
  WHERE f.empresa_id = p_empresa_id
    AND to_char(COALESCE(f.fecha_emision, f.fecha::date, f.fecha_factura::date), 'YYYY-MM') = p_period_month
    AND lower(trim(COALESCE(f.estado_cobro, ''))) = 'cobrada'
    AND f.deleted_at IS NULL;

  SELECT
    COALESCE(sum(
      public.round_half_even(
        GREATEST(
          COALESCE(COALESCE(g.total_eur, g.total_chf), 0) -
          CASE
            WHEN g.iva IS NULL OR g.iva <= 0 THEN 0
            ELSE g.iva
          END,
          0
        ),
        2
      )
    ), 0)::numeric(18,2)
  INTO v_gastos
  FROM public.gastos g
  WHERE g.empresa_id = p_empresa_id
    AND to_char(g.fecha::date, 'YYYY-MM') = p_period_month
    AND g.deleted_at IS NULL;

  v_ebitda := public.round_half_even(v_ingresos - v_gastos, 2)::numeric(18,2);

  INSERT INTO public.finance_kpi_snapshots (
    empresa_id,
    period_month,
    ingresos_operacion,
    gastos_operacion,
    ebitda,
    last_recalculated_at
  )
  VALUES (
    p_empresa_id,
    p_period_month,
    v_ingresos,
    v_gastos,
    v_ebitda,
    now()
  )
  ON CONFLICT (empresa_id, period_month)
  DO UPDATE SET
    ingresos_operacion = EXCLUDED.ingresos_operacion,
    gastos_operacion = EXCLUDED.gastos_operacion,
    ebitda = EXCLUDED.ebitda,
    last_recalculated_at = EXCLUDED.last_recalculated_at;
END;
$$;

CREATE OR REPLACE FUNCTION public.recalculate_monthly_kpis()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_old_empresa uuid;
  v_new_empresa uuid;
  v_old_month text;
  v_new_month text;
BEGIN
  IF TG_TABLE_NAME = 'facturas' THEN
    IF TG_OP IN ('UPDATE', 'DELETE') THEN
      v_old_empresa := OLD.empresa_id;
      v_old_month := to_char(COALESCE(OLD.fecha_emision, OLD.fecha::date, OLD.fecha_factura::date), 'YYYY-MM');
    END IF;
    IF TG_OP IN ('INSERT', 'UPDATE') THEN
      v_new_empresa := NEW.empresa_id;
      v_new_month := to_char(COALESCE(NEW.fecha_emision, NEW.fecha::date, NEW.fecha_factura::date), 'YYYY-MM');
    END IF;
  ELSIF TG_TABLE_NAME = 'gastos' THEN
    IF TG_OP IN ('UPDATE', 'DELETE') THEN
      v_old_empresa := OLD.empresa_id;
      v_old_month := to_char(OLD.fecha::date, 'YYYY-MM');
    END IF;
    IF TG_OP IN ('INSERT', 'UPDATE') THEN
      v_new_empresa := NEW.empresa_id;
      v_new_month := to_char(NEW.fecha::date, 'YYYY-MM');
    END IF;
  END IF;

  IF v_old_empresa IS NOT NULL AND v_old_month IS NOT NULL THEN
    PERFORM public._upsert_monthly_kpis(v_old_empresa, v_old_month);
  END IF;

  IF v_new_empresa IS NOT NULL
     AND v_new_month IS NOT NULL
     AND (v_new_empresa IS DISTINCT FROM v_old_empresa OR v_new_month IS DISTINCT FROM v_old_month) THEN
    PERFORM public._upsert_monthly_kpis(v_new_empresa, v_new_month);
  END IF;

  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_recalculate_monthly_kpis_facturas ON public.facturas;
CREATE TRIGGER trg_recalculate_monthly_kpis_facturas
AFTER INSERT OR UPDATE OR DELETE
ON public.facturas
FOR EACH ROW
EXECUTE FUNCTION public.recalculate_monthly_kpis();

DROP TRIGGER IF EXISTS trg_recalculate_monthly_kpis_gastos ON public.gastos;
CREATE TRIGGER trg_recalculate_monthly_kpis_gastos
AFTER INSERT OR UPDATE OR DELETE
ON public.gastos
FOR EACH ROW
EXECUTE FUNCTION public.recalculate_monthly_kpis();

COMMIT;
